version: '3'
services:
  web:
    build: .
    command: python -u run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - web-variables.env
  db:
    image: mongo:4.2-bionic
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
